### ISSUE TITLE
Would you update your code with the current htmd version ?

### ISSUE THREAD

**Issue by tbwxmu** [compsciencelab/ligdream#1]
Now, it is difficult to repeat your work as some module disappear, such as the " htmd.smallmol.smallmol".

**Comment by giadefa** [comment]
use an earlier release of HTMD

**Comment by miha-skalic** [comment]
Hi @tbwxmu ,

in the future we might update the repository to be compatible with latest HTMD version, but for now please use HTMD==1.13.9.
